name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  init:
    runs-on: ubuntu-latest
    env:
      REDIS_HOST: ${{ github.REDIS_HOST }}
      REDIS_PORT_INSIDE: ${{ github.REDIS_PORT_INSIDE }}
      REDIS_PORT_OUTSIDE: ${{ github.REDIS_PORT_OUTSIDE }}
    steps:
       - uses: actions/checkout@v3
       - name: Build docker compose
         run: docker compose up -d
       - name: build project
         run: npm run build
       - name: ESlinter
         run: npm run lint
       - name: unit tests
         run: npm run test